# Generated by Django 4.1.4 on 2023-02-26 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('adminid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.TextField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('studentid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('studentname', models.TextField(max_length=100)),
                ('studentphone', models.TextField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Washingmachine',
            fields=[
                ('machineNo', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('machineType', models.TextField(max_length=50)),
                ('machineLocation', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('laundrydate', models.DateField(blank=True, null=True)),
                ('starttime', models.TimeField(blank=True, null=True)),
                ('endtime', models.TimeField(blank=True, null=True)),
                ('machineNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.washingmachine')),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.student')),
            ],
        ),
    ]
