# Generated by Django 4.1.4 on 2023-02-27 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_book'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
