# Generated by Django 4.1.4 on 2023-02-27 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_delete_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lecturer',
            fields=[
                ('lectid', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.TextField(max_length=8)),
            ],
        ),
    ]
